name: Generate pacman animation
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout main
        uses: actions/checkout@v6

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: move svg to profile folder
        run: |
          mkdir -p profile
          cp dist/pacman-contribution-graph.svg profile/
          cp dist/pacman-contribution-graph-dark.svg profile/

      - name: commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update pacman contribution graph" || exit 0
          git push
